### ISSUE TITLE
phonetic recognition

### ISSUE THREAD

**Issue by pankaj2701** [NervanaSystems/aeon#42]
I want use neon for phoneme based speech recognition. But I am not able to figure out how to specify the phoneme set as the alphabet. 
It appears that aeon accepts a string of unique characters as alphabet. However the english phoneme set "AH AH AA AE AO AW B ...... " consists of repeated characters. 

I then mapped the phonemes to single letters of the english alphabet by trying to use both small and capital letters.   Eg I mapped AH to 'a 'and AA to 'A'. This passes and the training continues. But internally aeon converts all small case letters to upper when both small and upper case are present in the alphabet. And hence all results are misleading.

Any workaround?

**Comment by apark263** [comment]
We plan to overhaul text transformations at some point after we refactor the provider code.  For now you can remove `std::toupper` in two locations to make sure that your alphabet and transcript are treated case-sensitively:

HERE:
https://github.com/NervanaSystems/aeon/blob/master/loader/src/etl_char_map.hpp#L72
https://github.com/NervanaSystems/aeon/blob/master/loader/src/etl_char_map.cpp#L30
