### ISSUE TITLE
c++ libraries not visible on mac

### ISSUE THREAD

**Issue by sampathchanda** [NervanaSystems/aeon#48]
While I am trying to install aeon on OSX using `pip install` , I am facing the following C++ library issues. It seems to be a issue with including some C++ flags.
```
 In file included from loader/src/block_iterator_sequential.cpp:16:
    In file included from loader/src/block_iterator_sequential.hpp:18:
    loader/src/block_loader.hpp:17:10: fatal error: 'random' file not found
    #include <random>
             ^
    In file included from loader/src/batch_iterator.cpp:16:
    In file included from loader/src/batch_iterator.hpp:20:
    loader/src/buffer_in.hpp:19:10: fatal error: 'thread' file not found
    #include <thread>
             ^
    1 error generated.
    1 error generated.
```
Related link, suggesting solution:
`http://stackoverflow.com/questions/16229297/why-is-the-c-standard-library-not-working`

It would be great, if these C++ flags are incorporated automatically.

**Comment by sampathchanda** [comment]
I fixed the issue temporarily on my local system by changing the line:

`export CFLAGS="-Wno-deprecated-declarations -std=c++11"`
to
`export CFLAGS="-Wno-deprecated-declarations -std=c++11 -stdlib=libc++"`

in the file `env.sh`.

For this, I could not use the pip install directly.
```
Steps followed, for installation:
1. git clone <aeon_repository url>
2. change env.sh
3. python setup.py install
```

**Comment by eisneim** [comment]
@sampathchanda when i add `stdlib=libc++` this error happens:
```
 clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```
why and how to solve this? thanks

**Comment by eisneim** [comment]
my problem solved by add deployment_target env-var
```
$ MACOSX_DEPLOYMENT_TARGET=10.9 python3 setup.py install
```

**Comment by kohn1001** [comment]
Thanks eisneim  ! worked for me as well on my Mac!

My version is 10.12 and python2, so just to add another example: 
`$ MACOSX_DEPLOYMENT_TARGET=10.12 python2 setup.py install`
