### ISSUE TITLE
error in loader: alphabet does not consist of unique chars

### ISSUE THREAD

**Issue by anonymous-u** [NervanaSystems/aeon#51]
I am trying to train a model with audio and transcription data that are not in english using deep speech code. To load the transcription data, I need an alphabet containing utf-8 characters. 
(alphabet = u"_'АБВГДЕЁЖЗИЙКЛМНОӨПРСТУҮФХЦЧШЩЪЬЫЭЮЯ ")
I don't know how to pass config variable containing unicode string to dataloader.py.
When I try to train, I get following error:

Traceback (most recent call last):
  File "deepspeech/speech/train.py", line 134, in <module>
    train = DataLoader(backend=be, config=train_cfg_dict)
  File "/home/ubuntu/neon/.venv2/local/lib/python2.7/site-packages/aeon/dataloader.py", line 66, in __init__
    self.loader = self._start(json.dumps(config, ensure_ascii=False).encode('utf-8'), backend)
  File "/home/ubuntu/neon/.venv2/local/lib/python2.7/site-packages/aeon/dataloader.py", line 127, in _start
    self._raise_loader_error()
  File "/home/ubuntu/neon/.venv2/local/lib/python2.7/site-packages/aeon/dataloader.py", line 106, in _raise_loader_error
    self.loaderlib.get_error_message()
aeon.dataloader.LoaderRuntimeError: error in loader: alphabet does not consist of unique chars _'АБВГДЕЁЖЗИЙКЛМНОӨПРСТУҮФХЦЧШЩЪЬЫЭЮЯ 

I also tried by changing parameters of _start function in the dataloader.py file, since I am using unicode string: 
self.loader = self._start(json.dumps(config, ensure_ascii=False).encode('utf-8'), backend).

But still getting same error. Could you tell me how to solve this error?

**Comment by pzelazko-intel** [comment]
@anonymous-u It seems like you are using `master` branch. We've added support for unicode characters in `rc1-master` branch.

**Comment by anonymous-u** [comment]
Thanks for your response. 

Can you tell me how to install from rc1-master branch?
I cloned aeon and chose rc1-master branch by $ git checkout -b rc1-master command.
Following the aeon documentation I run 
$ mkdir -p aeon/build && cd $_ && cmake .. && pip install . 
command, but it gives an error:
CMake Error: The source directory "/home/ubuntu/aeon" does not appear to contain CMakeLists.txt.

On Readme.md file, it says that to install aeon, execute 
pip install git+https://github.com/Nervanasystems/aeon.git 
inside virtual environment. And after executed that command I tried to train, but it gives me the same error.

**Comment by rkimballn1** [comment]
You want to checkout the rc1-master branch with
`git checkout rc1-master`
without the -b option.

**Comment by anonymous-u** [comment]
Oh, I get it. thanks.

But there is one more thing. I don't understand how to install it correctly because after I built it,  it gives me an error when I try to use aeon from python;
      
Traceback (most recent call last):
  File "/home/ubuntu/deepspeech/speech/train.py", line 24, in <module>
     from aeon.dataloader import DataLoader
ImportError: dynamic module does not define init function (initaeon)

I think the reason is that there is no aeon folder in ~/neon/.venv2/local/lib/python2.7/site-packages/ directory. But pip install from master branch generates aeon folder in that directory.
So, I also tried running
$ pip install git+https://github.com/NervanaSystems/aeon.git@rc1-master command 
inside virtual environment . But it gives me an error:
IOError: [Errno 2] No such file or directory: '/tmp/pip-Id5QRG-build/setup.py error.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Id5QRG-build/

Could you give me more description on this?

**Comment by pzelazko-intel** [comment]
@anonymous-u Did you run `pip install .` after running cmake? Here is the installation instruction: https://github.com/NervanaSystems/aeon/tree/rc1-master#to-install-aeon. Also, it would be best if you removed old version of aeon at first.
