### ISSUE TITLE
How to disable upper case.

### ISSUE THREAD

**Issue by w4-kang** [NervanaSystems/aeon#53]
It seems to aeon audio data loader replaces characters in transcript to uppercase.
But I'd like to keep it lower case.
Is there any options for disabling it or workaround?
Or if it can't, how many special characters it supports?
What I'm trying to do convert lower character to special character.
(`rc1-master` can't be a solution in my case. In my environment, `rc1-master` got problem with opencv in install phase.)

**Comment by tsocha** [comment]
Did you try to add lower case characters to the alphabet?

**Comment by w4-kang** [comment]
Inside Aeon code, it forces to convert lower case to upper case. My problem was that I need to distinguish upper case and lower case alphabet.
But I solve it with replace lower case alphabet to special characters such as !"#$%&...@ which have lower index than ABC in ascii code table (It seems to there are not allowed character between [\]^_` in ascii code table).
Close issue.
