### ISSUE TITLE
Unable to install aeon

### ISSUE THREAD

**Issue by pabutcher** [NervanaSystems/aeon#54]

**Comment by sfraczek** [comment]
Is there an issue?

**Comment by pabutcher** [comment]
Sorry I tried to delete the issue, when I realized SoX was not installed correctly. Github doesnt seem to let you.

However, now I have SoX installed correctly (it was missing libtools), and I am still unable to install Aeon. I have installed opencv, and it imports without error in python. SoX is not a python package, unless I need a python wrapper for it?

When I use:
install git+https://github.com/NervanaSystems/aeon.git

I get this error:

Command "/Users/Peter/anaconda/envs/neon/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/vh/tnfpx1150_1dlx74z8jwqn3w0000gs/T/pip-cHbBmU-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/vh/tnfpx1150_1dlx74z8jwqn3w0000gs/T/pip-cj_9tt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/vh/tnfpx1150_1dlx74z8jwqn3w0000gs/T/pip-cHbBmU-build/

I am attaching the full output. Any help would be appreciated!

[AeonInstallError.txt](https://github.com/NervanaSystems/aeon/files/1208536/AeonInstallError.txt)
