### ISSUE TITLE
Anaconda and aeon

### ISSUE THREAD

**Issue by shaofushih** [NervanaSystems/aeon#60]
Hi all,

Anyone tried to use Anaconda with aeon 1.0.0?
We are having a bunch of missing package problems.
For example cmake, curl, sox, etc. 

Still missing:
(VENV_PATH)/compiler_compat/ld: cannot find -lm
(VENV_PATH)/compiler_compat/ld: cannot find -lpthread
(VENV_PATH)/compiler_compat/ld: cannot find -lc

Would there be a plan to do an updated version of
http://aeon.nervanasys.com/index.html/getting_started.html
with Anaconda installation?

**Comment by sfraczek** [comment]
@ldurka can you please reply to this issue?

**Comment by ldurka** [comment]
@shaofushih @sfraczek here you can find how we compile and install Aeon with Anacoda
https://github.com/NervanaSystems/benchmarks/blob/master/Jenkins/Aeon/CI_Scripts/Prepare_environment.sh#L54-L60

And we validate Aeon with Anaconda only on Cento7.3 With python 2.7 and Ubuntu 14.04 with Python 2.7
