### ISSUE TITLE
Python not found, Build problem

### ISSUE THREAD

**Issue by protsenkovi** [NervanaSystems/aeon#61]
Hello, I am trying to build aeon with Intel python distribution on CentOS 7 and getting an error, which itself contrintuitive:
```
    -- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
    -- Found PythonInterp: /opt/intel/intelpython3/bin/python3.6 (found version "3.6.3")
    Python not found, Python interface not included
```

in the presence of PYTHON_LIBRARIES, PYTHON_INCLUDE_DIRS which are equal to
```
[user@host build]$ echo $PYTHON_LIBRARIES
/opt/intel/intelpython3/lib
[user@host build]$ echo $PYTHON_INCLUDE_DIRS
/opt/intel/intelpython3/include
```

What are the additional prerequisites for the compilation? Could you give any advice on how to resolve this issue?

Configuration:
- gcc 4.8.5, curl-develop, sox-develop installed
- cmake 3.6.1, clang 3.9 installed as in https://aeon.nervanasys.com/index.html/getting_started.html
- python 3.6

P.S.
Would this package work with Intel Phi 7120P?

**Comment by sfraczek** [comment]
Hi. Aeon has never been tested with intel python. Please use the version from CentOS repository. It seems to be searching for python3 development libraries. Feel free to reopen the issue if needed.
