### ISSUE TITLE
Import issue with Aeon using Intel Python

### ISSUE THREAD

**Issue by krak3nnn** [NervanaSystems/aeon#62]
I'm currently trying to use Aeon with Neon 2.4 and I'm having some issues importing. Neon imports perfectly fine but Aeon, the import hangs. To stop it, I have to kill the python PID. Here is the tail end of the output where the import hangs using python -v:

intelpython2/lib/python2.7/site-packages/numpy/core/info.py
import numpy.core.info # precompiled from /intelpython2/lib/python2.7/site-packages/numpy/core/info.pyc
dlopen("/intelpython2/lib/python2.7/site-packages/numpy/core/multiarray.so", 2);
dlopen("/intelpython2/lib/python2.7/lib-dynload/datetime.so", 2);
import datetime # dynamically loaded from /intelpython2/lib/python2.7/lib-dynload/datetime.so

Has anyone had this issue before?

**Comment by sfraczek** [comment]
Hi @krak3nnn, I'm sorry nobody has replied to your issue earlier. Would you like to share status? Have you tried newer version? Is it possible for your solution? We have been using ordinary python and never run into this problem. Does it still need attention or can I close the issue?

**Comment by sfraczek** [comment]
Hi,
aeon has never been tested with intel python and it is not planned at the moment. Please use the default OS's python distribution if possible. I will close the issue but feel free to reopen if needed.
