### ISSUE TITLE
Error in 'import aeon'

### ISSUE THREAD

**Issue by lixiangchun** [NervanaSystems/aeon#69]
```python
>>> import aeon

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.5/dist-packages/aeon.cpython-35m-x86_64-linux-gnu.so: undefined symbol: llvm_gcda_summary_info
```

**Comment by sfraczek** [comment]
Please build aeon **without** setting the COVERAGE flag ON in production.  We have confirmed that aeon python bindings don't work with the error message you got when built with COVERAGE flag. Please note that this flag is for development only and we will update the documentation accordingly in next release. 
Can I close the issue?

**Comment by lixiangchun** [comment]
Thanks. It works now.
